### PR TITLE
updates to scheduler web ui for #1893

### PR DESCRIPTION
**Pull request by proddy**
still work in progress to make sure everything works, and then add the LL. translations

### CODE REVIEW

**Comment by proddy** [comment]
going to merge this to fix the bootloop, its the quickest way

**Comment by MichaelDvP** [comment]
Scheduler looks nice, but i can't change the scheduler type. Only when adding a new scheduler.

**Comment by MichaelDvP** [comment]
Also on newschedule i can toggle the buttons and  set to undefined state, showing odd options.

**Comment by proddy** [comment]
I'll take a look. You can't change the scheduler type when editing, I did this by design. We can change it back, but needs some more code to reset fields to their default (as time is used for a time and also a cmd).

**Comment by proddy** [comment]
> Also on newschedule i can toggle the buttons and set to undefined state, showing odd options.

can't reproduce - can you give an example?

**Comment by MichaelDvP** [comment]
grafik

**Comment by MichaelDvP** [comment]
I think the scheduler type buttons should react as radiobutton, not as togglebutton.

**Comment by proddy** [comment]
ok, I made https://github.com/emsesp/EMS-ESP32/pull/1901 to track

**Pull request merged**
