### PR TITLE
Polish translation update

### PR DESCRIPTION
**Pull request by pswid**

### CODE REVIEW

**Comment by proddy** [comment]
I removed the word "Account" for a reason

```
 ADMIN: 'Admin Account', 
 GUEST: 'Hosť Account'
```

Can you think of a better way that works for Polish? Perhaps put the type in brackets after the name?

**Comment by pswid** [comment]
What reason? In the current version the word "account" was not translated, now (at least in Polish) it makes sense (_admin account_ = _konto administratora_). PR does not change anything in other languages, although it allows you to translate the entire phrase _admin/guest account_ (if needed).

**Comment by proddy** [comment]
Keep the ADMIN and GUEST translations to show the real translations for the words Admin and Guest as before.

Then remove showing the type of the User in the popbox box. That's the easiest fix for everyone.

**Comment by proddy** [comment]
I'll make the changes

**Pull request merged**
