### PR TITLE
add EMS+ holidaymodes for RC310 

### PR DESCRIPTION
**Pull request by tp1de**
telegram type id's 0x269 to 0x26D for holiday modes 1-5 (hm1 to hm5).

see #275

### CODE REVIEW

**Comment by tp1de** [comment]
I tried to do my best explaining the functionality in #275 - see last entry.
As explained the parameters and the assigned-to variables do not initiate any telegram.
These parameters are taken when one of the five holiday start-stop dates are changed by the change value dialog box.
(this to avoid to have this variables 5 times and to allow to have different settings per holiday-mode) 

To visualize the parameters set per holiday-mode - either by ems-esp or by thermostat or km200 / App) the are visualized next to start-stop date within hm1 to hm5. --> see screenshots in #275

**Comment by proddy** [comment]
ok @MichaelDvP , I'll take a deeper look into this. I was concerned it's not following the guidelines or vision of ems-esp and I really don't like to see JSON as input strings for a value change. I'd rather create a new UI method for inputting these complex settings than force json parsing. I do appreciate the complexity and work that Thomas put into this so sure we'll find a way to accommodate this requirement,

**Comment by tp1de** [comment]
@proddy just to be clear the hm1 to hm5 text strings are not JSON. I just take the first part (start-stop date) for input:
**01.01.2023-01.02.2023**  : {3,,2,[hc1,hc2,dhw1]}
The rest   _: {3,,2,[hc1,hc2,dhw1]}_ is ignored for input and just displayed for reference ...

**Comment by MichaelDvP** [comment]
@tp1de yes, you  have described it, but i doubt that this way is usefull. 
Programming holidays is usefull if you have no access to the heating on start/end-days. But with ems-esp we have always access and it's much easier to set the heating to right mode at the time. Also with ioBroker/HA/... it's easy to setup a individual rule and schedule. The programming in thermostat is for all possibilitys a heating can do, it's a lot of parameters and the more parameters have to be set, someone makes errors or forget something to set. 
But this is only my opinion and i dont have RC300. If other users like the way and it works, it's ok for me.
Iwould prefere a single string for each HM(1-5) containing all settings. It's a complicated string, but if accepted, all parameters are set correctly with asingle command. And this function is imo very rarly used.

You read the hc settings on first time the telegram is received, how to make sure that a this point all hcs are detected?
When setting a hc assign this is only stored in telegram on a date-change later, But (if i interprete the code right) the not stored and not active assign is shown in the hm-string, this will lead to errors if someone first set the date and than the assigns/modes.

PS: You should auto-format the new code after all additions/changes (Press in VSC-Editor: Shift-Alt-F).

**Comment by tp1de** [comment]
Multiline is working with b3:
image

**Comment by tp1de** [comment]
Multiline v2:

image

**Comment by tp1de** [comment]
I will close since you are not interested.

**Comment by tefracky** [comment]
Is it somewhere implemented? I am very interested in the holiday-mode for the RC300.

**Comment by tp1de** [comment]
> Is it somewhere implemented? I am very interested in the holiday-mode for the RC300

Yes I tested it and made a pull request. @proddy and @MichaelDvP where not in favor to implement this solution so a closed the PR. If you want to test you need to compile from my forked repository: https://github.com/tp1de/EMS-ESP32/tree/dev
But read carefully my comments and explanations from above !

**Comment by tefracky** [comment]
> > Is it somewhere implemented? I am very interested in the holiday-mode for the RC300
> 
> Yes I tested it and made a pull request. @proddy and @MichaelDvP where not in favor to implement this solution so a closed the PR. If you want to test you need to compile from my forked repository: https://github.com/tp1de/EMS-ESP32/tree/dev But read carefully my comments and explanations from above !
> 
> P.S. I uploaded my latest b4 bin into my forked repository. You are free to test.

Thanks a lot, it works!

**Comment by proddy** [comment]
I'll re-look into the best way to implement this

**Pull request closed without merging**
