### PR TITLE
move HA climate to mqtt

### PR DESCRIPTION
**Pull request by MichaelDvP**
as mentioned in #368, please check if you like it and if it works with HA. 
It's not perfect, disable seltemp or mode is not checked.

### CODE REVIEW

**Comment by proddy** [comment]
It works, but the MQTT Discovery climate topic is created before the actual data is in the thermostat_data payload so HA will show the error:

 ```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1834
First occurred: 10:58:22 (2 occurrences)
Last logged: 11:07:00

Template variable error: 'value_json' is undefined when rendering '{{ value_json.hc1.seltemp }}'
```

I fixed this in the earlier version by only creating the climate topic when selemp and currtemp are ACTIVE

**Comment by MichaelDvP** [comment]
Oh, you're right, i have not checked this. The climate is builded with seltemp if roomtemp is missing, so it's always created on first publish. 
I will go back to my first approach, create a `hc->climate` which is set to
```
if (hasValue(hc->roomTemp)) {
   hc-climate = 1;
} else if (hasValue(hc->selTemp)) {
   hc->climate = 0;
} else {
   hc->climate = EMS_VALUE_UINT_NOTSET;
}
```
I had this first as hidden without long_name, but there is a bug that resets all flags of hidden value on every publish and i did not find this flag-reset. But as i read that domotics have mqtt-discovery, but no climate, maybe we can publish the hc->climate as enum, showing the seltemp/roomTemp status and make it possible to disable climate in customizations.
I'll rework this PR to check.

**Comment by MichaelDvP** [comment]
Ok, PR updated, please check now.

BTW: there were calls of `add_ha_climate(hc)` in settings telegrams where the mode is read, but the mode was never checked for climate creations, should there be a check?

**Comment by proddy** [comment]
that fixed the error in HA now. So works well.

Yes, we really only need to call add_ha_climate for those functions that populate the seltemp as like you said, without it the climate component is pretty useless.

Also I'm still thinking about #368 and how to detect the deviceValue instead of the actual value. When you exclude seltemp from the Customationzation web page it will still go ahead and create the climate topic since it has a value (it's only not visible or included in the thermostat_data payload)

**Pull request merged**
