### PR TITLE
Norwegian translation

### PR DESCRIPTION
**Pull request by Vikingn**

### CODE REVIEW

**Comment by proddy** [comment]
I will make a PR for this for only the NO changes since a lot has changed since the last update.

**Comment by proddy** [comment]
Hi @Vikingn - are you still planning to complete the Norwegian translations for the C++ entities? The file is `locale_translations.h`. Then we can move the 3.5.0 out of dev to main for our next major release. Let us know, thanks...

**Comment by Vikingn** [comment]
Hi Proddy ! Im working on the file. Im at line 483. Hope to be finished in 2-3 days.

**Comment by Vikingn** [comment]
How do we open it again ? I have the file...

**Comment by Vikingn** [comment]
Hi Proddy !Tried to add the file locale_translations.h now. Does it look ok ?

**Comment by MichaelDvP** [comment]
@Vikingn I've seen your latest translation in https://github.com/Vikingn/EMS-ESP32/blob/dev/src/locale_translations.h
Due to parallel translations of pl it's a bit tricky to merge. 
Should i add your translation together with pl to my dev and make a PR to your dev, than you can check the missing words in the latest version and make a new PR to this official version?

**Comment by proddy** [comment]
I was thining the same, I like Michael's approach

**Comment by MichaelDvP** [comment]
Corrected file (some pl-entities contains commas, making trouble when converting to csv)
[locale_translations.h.txt](https://github.com/emsesp/EMS-ESP32/files/9937567/locale_translations.h.txt)

**Comment by Vikingn** [comment]
The Norwegian is the last at right in each line after the swedish

**Comment by proddy** [comment]
we'll add it soon, I need to make some structural fixes first to the way we support the Polish language

**Pull request closed without merging**
