### PR TITLE
Update and fix translation

### PR DESCRIPTION
**Pull request by WiktorBuczko**

### CODE REVIEW

**Comment by MichaelDvP** [comment]
Wow, thanks. 
If you also like to check the entity translations i can make an actual excel sheet for easier editiing.

**Comment by WiktorBuczko** [comment]
Sure, I can do that

**Comment by MichaelDvP** [comment]
Creating the xls is also good to see formating errors, this is the corrected version from latest dev2:

[locale_translations.xlsx](https://github.com/emsesp/EMS-ESP32/files/13259095/locale_translations.xlsx)

**Comment by proddy** [comment]
If you want to merge this into dev2 @MichaelDvP then feel free to do so. Other option is to wait for the other translations in an XLS

**Comment by WiktorBuczko** [comment]
Polish translation completed

[locale_translations.xlsx](https://github.com/emsesp/EMS-ESP32/files/13259450/locale_translations.xlsx)

**Comment by proddy** [comment]
this is in Michael's dev2

**Comment by MichaelDvP** [comment]
Only the entity translation, the web translation from this PR is only in my testbuild with breaking changes to solar/mixer->water class. 
Please merge this PR to dev2 here.

**Pull request merged**
