### PR TITLE
Feature Moduline 400 WW settings and timer clock program

### PR DESCRIPTION
**Pull request by kwertie01**
In this PR I added new features for the Moduline 400 Thermostat. 

I added 5 parameters of the 0x3A telegram from the Moduline 400 (RC30) thermostat. (RC30wwSettings)

- wwmode
- wwwhenmodeoff
- wwdisinfect
- wwdisinfectday
- wwdisinfecthour

I added 7 parameters of the 0x40 telegram from the Moduline 400 (RC30) thermostat. (RC30Temp)

- heatingtype
- controlmode
- nighttemp
- daylowtemp
- daymidtemp
- daytemp
- holidaytemp

Added reading/writing of the switch points (switchtime1) of the Moduline 400 (RC30) clock program (0x3F telegram) including the following parameters:

- program
- pause
- party
- vacation
- holiday

### CODE REVIEW

**Review by MichaelDvP — APPROVED** [review]
Looks good. 
While checking i've seen some old bugs: the RC20 also uses T1-T4, but masks wrong with `& 1` when reading and set_switchtemp checks input to max 3 instead of 4. I 'll fix this later, or, if you like, you can add to this PR.

**Comment by kwertie01** [comment]
I'm a little bit ashamed and must admit that I didn't test the set_switchtemp properly. You are right that this is not working correctly now. I can set it using a number <3 but not using the letter T in front and/or number 4.
I see indeed that the mask for RC20 is &1. (old bug)
I will change/fix this in this PR.

**Comment by proddy** [comment]
@MichaelDvP you can approve the Merge request if you're fine with the additions.

**Comment by kwertie01** [comment]
@MichaelDvP The (old) bug of the RC20 mask and the set_switchtemp for the RC30 are fixed.

**Comment by MichaelDvP** [comment]
Thanks, only one remark:
The RC20 also have T1-T4, please set in line 2501 max_on = 4, then you don't need the if for RC30. And you can set the RC20 text to FL_(nighttemp1) (line 3697) to make it perfect.

**Comment by kwertie01** [comment]
I saw your remark too late and already created the `disable usage of T0 for RC30 in set_switchtime` commit.
In the second commit, I implemented your remarks.

**Comment by proddy** [comment]
done! nice work chaps

**Pull request merged**
