### PR TITLE
Web changes #1920

### PR DESCRIPTION
**Pull request by proddy**
Many small web updates and optimizations as listed in #1920 

plus:

- fix WiFi scan with AP
- added Unit tests for console commands

### CODE REVIEW

**Comment by MichaelDvP** [comment]
custom entities adding does notwork. Dialog is ok, but in the list the new entity is instantly removed (i guess from refresh).

**Comment by proddy** [comment]
oops. will check.

**Comment by MichaelDvP** [comment]
from #1920:
> Only remaining issue seems to be the Upload progress bar.

Seems the progress.total/loaded always stays zero. 
A fast workaround is check `isUploading` and just use text LL.UPLOADING and set progressbar to "indeterminate"
better than no feedback at all.

**Comment by proddy** [comment]
> from #1920:
> 
> > Only remaining issue seems to be the Upload progress bar.
> 
> Seems the progress.total/loaded always stays zero. A fast workaround is check `isUploading` and just use text LL.UPLOADING and set progressbar to "indeterminate" better than no feedback at all.

I think that's a good and only workaround for now. I've informed the Alova team about it not working in v3 and then created some demo code to show it breaking (https://codesandbox.io/p/devbox/alova-test-upload-w46x26?file=%2Fsrc%2Fapi.ts) but it seems to be working fine, which is embarrassing. So something else is messing the react hooks & children propagation so next step is to change the demo code to also use a new component like our SingleUpload.tsx and see if the state is passed through correctly.

**Comment by MichaelDvP** [comment]
The upload  button is imo a step backward. Drag&Drop was nice.
The progressbar still shows 0 and does not move.

**Comment by proddy** [comment]
progressbar is fixed (was an alova bug). Drag&Drop was nice but not useful on phones or tablets. I also found it dangerous to use. And it added 12kb to the web bundle (6kb gzipped).

**Comment by proddy** [comment]
ok, wrote my own Drag & Drop. Needs some more testing and validation but its nicer and easier

**Comment by proddy** [comment]
Think it's finished. ready to commit. If you want @MichaelDvP to take one last check.

**Comment by MichaelDvP** [comment]
The autorefresh is great, but still in custom entities it reverts all adds/changes made in the dialog.

Upload works good with drag/drop. The needs-reboot banner stay while the reboot circle is shows, that's confusing.

**Comment by proddy** [comment]
Thanks for reviewing. I'll fix both those.

**Comment by MichaelDvP** [comment]
In settings you use headline "general options" for "force heatingoff", " remote" and "shower", in the docs of emsesp.org the headline is "special funnctions". Maybe sync both headlines.

**Comment by proddy** [comment]
> In settings you use headline "general options" for "force heatingoff", " remote" and "shower", in the docs of emsesp.org the headline is "special funnctions". Maybe sync both headlines.

I prefer "Special Functions". Shall I change it?

**Comment by MichaelDvP** [comment]
> I prefer "Special Functions". Shall I change it?

yes, please, i also prefer it.

**Comment by proddy** [comment]
done. If there are any other issues I can fix as we go along.

**Comment by MichaelDvP** [comment]
I'm still not very happy with the new upload. 
Before it was 
- click or drop file: progress until 100% then restarts with only circle shown

Now its:
- scroll down to upload
- click or drop file: filename is shown
- scroll down to see the upload button
- press button upload: progress to 100%, nothing seems to happen after that
- scoll down to see the banner
- click restart: wait, than there is only a toast-message "network disconnected", than the page is reloaded.

Most users does not update often, so it's ok. But for me it's annoying to make 6 interaction instead of 1.

**Comment by proddy** [comment]
I'll have to think about how to make it more intuitive. When the progress hits 100% it should be replaced with a Restart button or a banner. What do you suggest? The Network Disconnected is something I need to fix, related to the timeout I thnk. 

A few other points:

- Upload is not a highly used feature, as you said. I never use it. For developers it's faster to click on the upload button in VSCode or execute a `pio run -t upload`.
- This is why Upload is at the bottom of the page and Downloads are shown first
- Showing the filename is important. Before you could drag and drop a hundred files and not know which one will be loaded. Selecting the wrong one could brick the system.
- Showing the upload button adds another safety check in case users accidentally does select the wrong file. It's common on systems (esphome, tasmota, amazon alexa, sonos, unifi all do this)
- Another idea is to add an automatic update like "Click to upgrade to the latest version" which does an automatic download and then upload & restart?
- It saves 6kb in flash this way. We need it for the new Web code that's coming (favourite dashboard, PV dashboard, timer/switch mapping). I also spent two whole days doing it!

**Comment by proddy** [comment]
made some minor improvements. Don't get the Network Timeout though. If you still see this (after a browser cache refresh or restart) let me know. Timeout is 1 minute (api/system.ts).

**Comment by MichaelDvP** [comment]
> Showing the filename is important. Before you could drag and drop a hundred files and not know which one will be loaded. Selecting the wrong one could brick the system.

Normally not, the bin is checked for right processor binary and size. maybe you can upload a tasmota esp32 binary, but i think this will run and is not  bricking.

**Comment by proddy** [comment]
I was referring to json setting files or schedule configurations

**Pull request merged**
