### PR TITLE
Fix Swedish - #874 and #875

### PR DESCRIPTION
**Pull request by proddy**

### CODE REVIEW

**Review by MichaelDvP — APPROVED** [review]
Looks all ok, but i doubt that this fixes #874.
If this was the cause all plurals should wrongin SE, but all plurals working for SE, except days. Also many days are working for SE, only for 2, few it's wrong. 
Now look at the plural declaration in PL and find the difference between days and all other num declarations.

**Comment by proddy** [comment]
> Looks all ok, but i doubt that this fixes #874. If this was the cause all plurals should wrongin SE, but all plurals working for SE, except days. Also many days are working for SE, only for 2, few it's wrong. Now look at the plural declaration in PL and find the difference between days and all other num declarations.

The plurals are handled by the Intl JS library base do rules per locale, which typescript-i18n used. When it was SE it was using the Sami language. I'm not sure why it worked in the dashboard and not in the status. It's also not just NUM_DAYS but also NUM_MINUTES and the others too.

**Comment by proddy** [comment]
For PL it's weird how it's implemented and I think incorrectly. I found out that numeric plurals in Polish are tricky (see https://www.quora.com/How-do-Polish-plurals-work) but the library should handle this and not be implemented the way it is now.

**Comment by MichaelDvP** [comment]
> When it was SE it was using the Sami language. I'm not sure why it worked in the dashboard and not in the status. It's also not just NUM_DAYS but also NUM_MINUTES and the others too.

Very strange, i did not see issues for the plurals when switching language. But plural rules for se and sv are identical. See http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html

I also don't know what have caused it and did not see it in dashboard for any wrong plural (including days)  and in status minutes and seconds were ok for all languages (including SE), i thought it's just days, let's wait 2 days if it is fixed.

**Comment by proddy** [comment]
I hope it's fixed but we'll see. I quick test I did was
- add `**{LL.NUM_MINUTES({num: 2})}**` to the bottom of `SignIn.tsx`
- Make the PL translation the same as EN in `i18n/pl/index.ts` just to rule out the base translation messing the formatting up
- `npm run standalone` and click on the flags and see how the number is rendered
- it didn't work for Swedish when it was set to `se`

**Pull request merged**
