### PR TITLE
remove "message" from device/values

### PR DESCRIPTION
**Pull request by MichaelDvP**

### CODE REVIEW

**Comment by proddy** [comment]
just saw this, is it still needed?

**Comment by MichaelDvP** [comment]
If you have removed the message, it is not needed. 
But i thought you can keep the message and/or also add the message in emsdevice/get_value_info back and this is shown if no commandfunction is found. On valid commandfunction the command can fill the output from scratch. Make is safe for future messages.

**Comment by proddy** [comment]
the message is gone, but the logic is still there so what you see in the LOG console and JSON message is the same. This is the result when running `test` in Telnet. the test called "api3" tries to think of all scenarios to make sure I didn't miss anything.

```
ems-esp:# test api3

web output: [/api/boiler] (200) {"reset":"","heatingoff":false,"heatingactive":false,"tapwateractive":true,"selflowtemp":0,"curflowtemp":60.2,"rettemp":48.1,"syspress":1.4,"burngas":true,"burngas2":false,"flamecurr":37.4,"fanwork":true,"ignwork":false,"oilpreheat":false,"heatingpump":true,"selburnpow":115,"curburnpow":61,"ubauptime":3940268,"servicecode":"=H","servicecodenumber":201,"nompower":0,"nrgtotal":0.0,"nrgheat":0.0,"dhw":{"seltemp":52,"comfort":"hot","flowtempoffset":40,"circpump":false,"chargetype":"3-way valve","hyston":-5,"hystoff":0,"disinfectiontemp":70,"circmode":"off","circ":false,"storagetemp1":53.8,"activated":true,"3wayvalve":true,"nrg":0.0}}

web output: [/api/boiler/commands] (200) {"boil2hystoff":"hysteresis stage 2 off temperature","boil2hyston":"hysteresis stage 2 on temperature","boilhystoff":"hysteresis off temperature","boilhyston":"hysteresis on temperature","burnmaxpower":"burner max power","burnminperiod":"burner min period","burnminpower":"burner min power","coldshot":"send a cold shot of water","commands":"list all commands","curvebase":"heatingcurve base","curveend":"heatingcurve end","curveon":"heatingcurve on","dhw[n].activated":"activated","dhw[n].chargeoptimization":"charge optimization","dhw[n].circ":"circulation active","dhw[n].circmode":"circulation pump mode","dhw[n].circpump":"circulation pump available","dhw[n].comfort":"comfort","dhw[n].comfort1":"comfort mode","dhw[n].disinfecting":"disinfecting","dhw[n].disinfectiontemp":"disinfection temperature","dhw[n].flowtempoffset":"flow temperature offset","dhw[n].hystoff":"hysteresis off temperature","dhw[n].hyston":"hysteresis on temperature","dhw[n].maxpower":"max power","dhw[n].maxtemp":"maximum temperature","dhw[n].nrg":"energy","dhw[n].onetime":"one time charging","dhw[n].seltemp":"selected temperature","dhw[n].seltemplow":"selected lower temperature","dhw[n].seltempsingle":"single charge temperature","dhw[n].tapactivated":"turn on/off","dhw[n].tempecoplus":"selected eco+ temperature","emergencyops":"emergency operation","emergencytemp":"emergency temperature","entities":"list all entities","heatingactivated":"heating activated","heatingoff":"force heating off","heatingtemp":"heating temperature","info":"list all values","maintenance":"maintenance scheduled","maintenancedate":"next maintenance date","maintenancetime":"time to next maintenance","nofrostmode":"nofrost mode","nofrosttemp":"nofrost temperature","nompower":"nominal Power","nrgheat":"energy heating","pumpcharacter":"boiler pump characteristic","pumpdelay":"pump delay","pumpmode":"boiler pump mode","pumpmodmax":"boiler pump max power","pumpmodmin":"boiler pump min power","reset":"reset","selburnpow":"burner selected max power","selflowtemp":"selected flow temperature","summertemp":"summer temperature"}

web output: [/api/boiler/values] (200) {"reset":"","heatingoff":false,"heatingactive":false,"tapwateractive":true,"selflowtemp":0,"curflowtemp":60.2,"rettemp":48.1,"syspress":1.4,"burngas":true,"burngas2":false,"flamecurr":37.4,"fanwork":true,"ignwork":false,"oilpreheat":false,"heatingpump":true,"selburnpow":115,"curburnpow":61,"ubauptime":3940268,"servicecode":"=H","servicecodenumber":201,"nompower":0,"nrgtotal":0.0,"nrgheat":0.0,"dhw":{"seltemp":52,"comfort":"hot","flowtempoffset":40,"circpump":false,"chargetype":"3-way valve","hyston":-5,"hystoff":0,"disinfectiontemp":70,"circmode":"off","circ":false,"storagetemp1":53.8,"activated":true,"3wayvalve":true,"nrg":0.0}}

web output: [/api/boiler/info] (200) {"reset (reset)":"","force heating off (heatingoff)":false,"heating active (heatingactive)":false,"tapwater active (tapwateractive)":true,"selected flow temperature (selflowtemp)":0,"current flow temperature (curflowtemp)":60.2,"return temperature (rettemp)":48.1,"system pressure (syspress)":1.4,"gas (burngas)":true,"gas stage 2 (burngas2)":false,"flame current (flamecurr)":37.4,"fan (fanwork)":true,"ignition (ignwork)":false,"oil preheating (oilpreheat)":false,"heating pump (heatingpump)":true,"burner selected max power (selburnpow)":115,"burner current power (curburnpow)":61,"total UBA operating time (ubauptime)":"2736 days 7 hours 8 minutes","service code (servicecode)":"=H","service code number (servicecodenumber)":201,"dhw selected temperature (seltemp)":52,"dhw comfort (comfort)":"hot","dhw flow temperature offset (flowtempoffset)":40,"dhw circulation pump available (circpump)":false,"dhw charging type (chargetype)":"3-way valve","dhw hysteresis on temperature (hyston)":-5,"dhw hysteresis off temperature (hystoff)":0,"dhw disinfection temperature (disinfectiontemp)":70,"dhw circulation pump mode (circmode)":"off","dhw circulation active (circ)":false,"dhw storage intern temperature (storagetemp1)":53.8,"dhw activated (activated)":true,"dhw 3-way valve active (3wayvalve)":true,"nominal Power (nompower)":0,"total energy (nrgtotal)":0.0,"energy heating (nrgheat)":0.0,"dhw energy (nrg)":0.0}

web output: [/api/boiler/entities] (200) {"heatingoff":["force heating off"],"heatingactive":["heating active"],"tapwateractive":["tapwater active"],"selflowtemp":["selected flow temperature","°C"],"heatingpumpmod":["heating pump modulation","%"],"outdoortemp":["outside temperature","°C"],"curflowtemp":["current flow temperature","°C"],"rettemp":["return temperature","°C"],"switchtemp":["mixing switch temperature","°C"],"syspress":["system pressure","bar"],"boiltemp":["actual boiler temperature","°C"],"headertemp":["low loss header","°C"],"exhausttemp":["exhaust temperature","°C"],"burngas":["gas"],"burngas2":["gas stage 2"],"flamecurr":["flame current","µA"],"fanwork":["fan"],"ignwork":["ignition"],"oilpreheat":["oil preheating"],"burnminpower":["burner min power","%"],"burnmaxpower":["burner max power","%"],"burnminperiod":["burner min period","minutes"],"absburnpow":["burner current power (absolute)","%"],"heatblock":["heating block","°C"],"boilhyston":["hysteresis on temperature","°C"],"boilhystoff":["hysteresis off temperature","°C"],"boil2hyston":["hysteresis stage 2 on temperature","°C"],"boil2hystoff":["hysteresis stage 2 off temperature","°C"],"curveon":["heatingcurve on"],"curvebase":["heatingcurve base","°C"],"curveend":["heatingcurve end","°C"],"summertemp":["summer temperature","°C"],"nofrostmode":["nofrost mode"],"nofrosttemp":["nofrost temperature","°C"],"heatingactivated":["heating activated"],"heatingtemp":["heating temperature","°C"],"heatingpump":["heating pump"],"pumpmodmax":["boiler pump max power","%"],"pumpmodmin":["boiler pump min power","%"],"pumpmode":["boiler pump mode"],"pumpcharacter":["boiler pump characteristic"],"pumpdelay":["pump delay","minutes"],"setflowtemp":["set flow temperature","°C"],"setburnpow":["burner set power","%"],"selburnpow":["burner selected max power","%"],"curburnpow":["burner current power","%"],"burnstarts":["burner starts"],"burnworkmin":["total burner operating time","minutes"],"burn2workmin":["burner stage 2 operating time","minutes"],"heatworkmin":["total heat operating time","minutes"],"heatstarts":["burner starts heating"],"ubauptime":["total UBA operating time","minutes"],"lastcode":["last error code"],"servicecode":["service code"],"servicecodenumber":["service code number"],"maintenancemessage":["maintenance message"],"maintenance":["maintenance scheduled"],"maintenancetime":["time to next maintenance","hours"],"maintenancedate":["next maintenance date"],"emergencyops":["emergency operation"],"emergencytemp":["emergency temperature","°C"],"meterheat":["meter heating","kWh"],"dhw.meter":["meter","kWh"],"gasmeterheat":["gas meter heating","kWh"],"dhw.gasmeter":["gas meter","kWh"],"nrgheat2":["energy heating 2","kWh"],"dhw.nrg2":["energy 2","kWh"],"dhw.tapactivated":["turn on/off"],"dhw.settemp":["set temperature","°C"],"dhw.seltemp":["selected temperature","°C"],"dhw.seltemplow":["selected lower temperature","°C"],"dhw.tempecoplus":["selected eco+ temperature","°C"],"dhw.seltempoff":["selected temperature for off","°C"],"dhw.seltempsingle":["single charge temperature","°C"],"dhw.solartemp":["solar boiler temperature","°C"],"dhw.type":["type"],"dhw.comfort":["comfort"],"dhw.comfort1":["comfort mode"],"dhw.flowtempoffset":["flow temperature offset","°C"],"dhw.chargeoptimization":["charge optimization"],"dhw.maxpower":["max power","%"],"dhw.maxtemp":["maximum temperature","°C"],"dhw.circpump":["circulation pump available"],"dhw.chargetype":["charging type"],"dhw.hyston":["hysteresis on temperature","°C"],"dhw.hystoff":["hysteresis off temperature","°C"],"dhw.disinfectiontemp":["disinfection temperature","°C"],"dhw.circmode":["circulation pump mode"],"dhw.circ":["circulation active"],"dhw.curtemp":["current intern temperature","°C"],"dhw.curtemp2":["current extern temperature","°C"],"dhw.curflow":["current tap water flow","l/min"],"dhw.storagetemp1":["storage intern temperature","°C"],"dhw.storagetemp2":["storage extern temperature","°C"],"dhw.activated":["activated"],"dhw.onetime":["one time charging"],"dhw.disinfecting":["disinfecting"],"dhw.charging":["charging"],"dhw.recharging":["recharging"],"dhw.tempok":["temperature ok"],"dhw.active":["active"],"dhw.3wayvalve":["3-way valve active"],"dhw.setpumppower":["set pump power","%"],"dhw.mixertemp":["mixer temperature","°C"],"dhw.cylmiddletemp":["cylinder middle temperature (TS3)","°C"],"dhw.starts":["starts"],"dhw.workm":["active time","minutes"],"nompower":["nominal Power","kW"],"nrgtotal":["total energy","kWh"],"nrgheat":["energy heating","kWh"],"dhw.nrg":["energy","kWh"]}

web output: [/api/boiler/comfort] (200) {"name":"comfort","fullname":"dhw comfort","circuit":"dhw","value":"hot","type":"enum","enum":["hot","eco","intelligent"],"readable":true,"writeable":true,"visible":true}

web output: [/api/boiler/comfort/value] (200) {"api_data":"hot"}

web output: [/api/boiler/comfort/fullname] (200) {"api_data":"dhw comfort"}

web output: [/api/boiler/outdoortemp] (200) {"name":"outdoortemp","fullname":"outside temperature","circuit":"","type":"number","uom":"°C","readable":true,"writeable":false,"visible":true}

web output: [/api/boiler/dhw/chargetype/writeable] (200) {"api_data":"false"}

web output: [/api/boiler/flamecurr/value] (200) {"api_data":"37.4"}

web output: [/api/custom] (200) {"test_custom":0.00,"test_read_only":0.00,"test_ram":"14","seltemp":"14"}

web output: [/api/custom/seltemp] (200) {"name":"seltemp","ram":1,"type":"number","readable":true,"writeable":true,"visible":true,"value":"14"}

web output: [/api/system] (200) {"System":{"version":"3.7.0-dev.26","uptime":"000+00:00:00.000","uptime (seconds)":0,"reset reason":"Unknown / Unknown"},"Network":{"network":"WiFi","hostname":"ems-esp","RSSI":-23,"TxPower setting":0,"static ip config":false,"low bandwidth":false,"disable sleep":false,"enable MDNS":true,"enable CORS":false},"NTP":{},"MQTT":{"MQTT status":"disconnected","MQTT publishes":0,"MQTT queued":0,"MQTT publish fails":0,"MQTT connects":1,"enabled":true,"client id":"ems-esp","keep alive":60,"clean session":false,"entity format":1,"base":"ems-esp","discovery prefix":"homeassistant","discovery type":0,"nested format":1,"ha enabled":true,"mqtt qos":0,"mqtt retain":false,"publish time heartbeat":60,"publish time boiler":10,"publish time thermostat":10,"publish time solar":10,"publish time mixer":10,"publish time water":0,"publish time other":10,"publish time sensor":10,"publish single":false,"publish2command":false,"send response":false},"Syslog":{"enabled":false},"Sensor":{"temperature sensors":2,"temperature sensor reads":0,"temperature sensor fails":0,"analog sensors":2,"analog sensor reads":0,"analog sensor fails":0},"API":{"API calls":13,"API fails":0},"Bus":{"bus status":"connected","bus protocol":"HT3","bus telegrams received (rx)":13,"bus reads (tx)":0,"bus writes (tx)":0,"bus incomplete telegrams":0,"bus reads failed":0,"bus writes failed":0,"bus rx line quality":100,"bus tx line quality":100},"Settings":{"board profile":"S32","locale":"en","tx mode":8,"ems bus id":11,"shower timer":false,"shower min duration":180,"shower alert":false,"hide led":false,"notoken api":false,"readonly mode":false,"fahrenheit":false,"dallas parasite":false,"bool format":1,"bool dashboard":1,"enum format":1,"analog enabled":true,"telnet enabled":true,"max web log buffer":50,"web log buffer":45},"Devices":[{"type":"boiler","name":"GBx72/Trendline/Cerapur/Greenstar Si","device id":"0x08","product id":123,"brand":"","version":"01.00","entities":37,"handlers received":"0x18","handlers fetched":"0x14 0x33","handlers pending":"0xBF 0x10 0x11 0xC2 0x15 0x1C 0x19 0x1A 0x35 0x34 0x2A 0xD1 0xE3 0xE4 0xE5 0xE9 0x2E 0x3B"},{"type":"thermostat","name":"RC300/RC310/Moduline 3000/1010H/CW400/Sense II/HPC410","device id":"0x10","product id":158,"brand":"","version":"01.00","entities":8,"handlers received":"0x02A5 0x031D","handlers pending":"0xA3 0x06 0xA2 0x12 0x13 0x02B9 0x02AF 0x029B 0x0471 0x02A6 0x02BA 0x02B0 0x029C 0x0472 0x02A7 0x02BB 0x02B1 0x029D 0x0473 0x02A8 0x02BC 0x02B2 0x029E 0x0474 0x02A9 0x02BD 0x02B3 0x029F 0x0475 0x02AA 0x02BE 0x02B4 0x02A0 0x0476 0x02AB 0x02BF 0x02B5 0x02A1 0x0477 0x02AC 0x02C0 0x02B6 0x02A2 0x0478 0x02CC 0x0467 0x02CE 0x0468 0x02D0 0x0469 0x02D2 0x046A 0x031E 0x0267"},{"type":"thermostat","name":"RC200/CW100/CR120","device id":"0x18","product id":157,"brand":"","version":"01.00","entities":8,"handlers received":"0x02A6","handlers pending":"0xA3 0x06 0xA2 0x12 0x13 0x02A5 0x02B9 0x02AF 0x029B 0x0471 0x02BA 0x02B0 0x029C 0x0472 0x02A7 0x02BB 0x02B1 0x029D 0x0473 0x02A8 0x02BC 0x02B2 0x029E 0x0474 0x02A9 0x02BD 0x02B3 0x029F 0x0475 0x02AA 0x02BE 0x02B4 0x02A0 0x0476 0x02AB 0x02BF 0x02B5 0x02A1 0x0477 0x02AC 0x02C0 0x02B6 0x02A2 0x0478 0x02CC 0x0467 0x02CE 0x0468 0x02D0 0x0469 0x02D2 0x046A 0x031D 0x031E 0x0267"}]}

web output: [/api/system/settings/locale] (200) {"value":"en"}

web output: [/api/scheduler/info] (200) {"test_scheduler":true}

web output: [/api/scheduler/test_scheduler] (200) {"name":"test_scheduler","type":"boolean","value":true,"command":"system/fetch","cmd_data":"10","readable":true,"writeable":true,"visible":true}

web output: [/api/temperaturesensor/test_sensor2] (200) {"id":"0B_0C0D_0E0F_1011","name":"test_sensor2","value":45.6,"type":"number","uom":"°C","writeable":false}

web output: [/api/temperaturesensor/0B_0C0D_0E0F_1011] (200) {"id":"0B_0C0D_0E0F_1011","name":"test_sensor2","value":45.6,"type":"number","uom":"°C","writeable":false}

web output: [/api/temperaturesensor/test_sensor2/value] (200) {"api_data":"45.6"}

web output: [/api/analogsensor] (200) {"test_analog1":0,"test_analog2":1}

web output: [/api/analogsensor/test_analog1] (200) {"gpio":36,"type":"number","analog":"adc","value":0,"writeable":false,"offset":0,"factor":0.1,"uom":"mV"}

web output: [/api/analogsensor/test_analog1/offset] (200) {"api_data":"0"}

**** Testing bad urls ****

web output: [/api/boiler2] (404) {"message":"unknown device boiler2"}

web output: [/api/boiler/bad] (400) {"message":"unknown command bad"}

web output: [/api/boiler/bad/value] (400) {"message":"unknown command bad/value"}

web output: [/api/boiler/comfort/valu] (400) {"message":"cannot find attribute in comfort"}

web output: [/api/system/settings/locale2] (400) {"message":"cannot find data in settings/locale2"}

web output: [/api/scheduler/test_scheduler2] (400) {"message":"cannot find test_scheduler2 in scheduler"}

web output: [/api/custom/seltemp2] (400) {"message":"cannot find seltemp2 in custom"}

web output: [/api/temperaturesensor/test_sensor20] (400) {"message":"cannot find test_sensor20 in temperaturesensor"}

web output: [/api/temperaturesensor/0B_0C0D_0E0F_XXXX] (400) {"message":"cannot find 0B_0C0D_0E0F_XXXX in temperaturesensor"}

web output: [/api/temperaturesensor/test_sensor2/bad] (400) {"message":"cannot find attribute in test_sensor2"}

web output: [/api/analogsensor/test_analog1/bad] (400) {"message":"cannot find attribute in test_analog1"}

web output: [/api/analogsensor/test_analog10] (400) {"message":"cannot find test_analog10 in analogsensor"}

web output: [/api/analogsensor/test_analog10/bad] (400) {"message":"cannot find test_analog10/bad in analogsensor"}
000+00:00:00.000 D 205: [analogsensor] ADC Sensor on GPIO 36
000+00:00:00.000 D 206: [analogsensor] Digital Read on GPIO 37
000+00:00:00.000 D 207: [temperaturesensor] Loading customization for temperature sensor 01_0203_0405_0607
000+00:00:00.000 D 208: [temperaturesensor] Loading customization for temperature sensor 0B_0C0D_0E0F_1011
000+00:00:00.000 D 209: [command] Fetched device entity/attributes for system/settings/locale/value
000+00:00:00.000 I 210: [system] Message: locale is en
000+00:00:00.000 I 211: [command] Calling command system/message (send a message) with value locale is en
000+00:00:00.000 D 212: [emsesp] Schedule command 'system/message' with data 'locale is en' was successful
000+00:00:00.000 D 213: [command] Fetched device entity/attributes for system/network/rssi/value
000+00:00:00.000 I 214: [system] Message: rssi is -23
000+00:00:00.000 I 215: [command] Calling command system/message (send a message) with value rssi is -23
000+00:00:00.000 D 216: [emsesp] Schedule command 'system/message' with data 'rssi is -23' was successful
000+00:00:00.000 D 217: [command] Fetched device entity/attributes for system/network/rssi/value
000+00:00:00.000 I 218: [system] Message: rssi is -23 dbm
000+00:00:00.000 I 219: [command] Calling command system/message (send a message) with value rssi is -23 dbm
000+00:00:00.000 D 220: [emsesp] Schedule command 'system/message' with data 'rssi is -23 dbm' was successful
000+00:00:00.000 D 221: [command] Fetched device entity/attributes for custom/seltemp/value
000+00:00:00.000 I 222: [system] Message: 14
000+00:00:00.000 I 223: [command] Calling command system/message (send a message) with value 14
000+00:00:00.000 D 224: [emsesp] Schedule command 'system/message' with data '14' was successful
000+00:00:00.000 D 225: [command] Fetched device entity/attributes for custom/seltemp/value
000+00:00:00.000 I 226: [system] Message: seltemp=14
000+00:00:00.000 I 227: [command] Calling command system/message (send a message) with value seltemp=14
000+00:00:00.000 D 228: [emsesp] Schedule command 'system/message' with data 'seltemp=14' was successful
000+00:00:00.000 D 229: [command] Fetched device entity/attributes for custom/seltemp/value
000+00:00:00.000 I 230: [system] Message: 14
000+00:00:00.000 I 231: [command] Calling command system/message (send a message) with value 14
000+00:00:00.000 D 232: [emsesp] Schedule command 'system/message' with data '14' was successful
000+00:00:00.000 D 233: [emsesp] [DEBUG] fetching single attribute value
000+00:00:00.000 W 234: [command] Command failed: unknown command outdoortemp/value
000+00:00:00.000 W 235: [command] Command message failed (Error)
000+00:00:00.000 W 236: [emsesp] Schedule test6: Command message failed (Error)
000+00:00:00.000 D 237: [emsesp] [DEBUG] fetching single attribute value
000+00:00:00.000 D 238: [command] Fetched device entity/attributes for boiler/flowtempoffset/value
000+00:00:00.000 I 239: [system] Message: 40
000+00:00:00.000 I 240: [command] Calling command system/message (send a message) with value 40
000+00:00:00.000 D 241: [emsesp] Schedule command 'system/message' with data '40' was successful
000+00:00:00.000 D 242: [emsesp] [DEBUG] fetching single attribute value
000+00:00:00.000 D 243: [command] Fetched device entity/attributes for boiler/flowtempoffset/value
000+00:00:00.000 I 244: [system] Message: 40
000+00:00:00.000 I 245: [command] Calling command system/message (send a message) with value 40
000+00:00:00.000 D 246: [emsesp] Schedule command 'system/message' with data '40' was successful
000+00:00:00.000 D 247: [emsesp] [DEBUG] fetching single attribute value
000+00:00:00.000 D 248: [command] Fetched device entity/attributes for boiler/storagetemp1/value
000+00:00:00.000 I 249: [system] Message: 53.8
000+00:00:00.000 I 250: [command] Calling command system/message (send a message) with value 53.8
000+00:00:00.000 D 251: [emsesp] Schedule command 'system/message' with data '53.8' was successful
000+00:00:00.000 D 252: [command] Fetched device entity/attributes for custom/seltemp/value
000+00:00:00.000 D 253: [emsesp] [DEBUG] fetching single attribute value
000+00:00:00.000 D 254: [command] Fetched device entity/attributes for boiler/flowtempoffset/value
000+00:00:00.000 I 255: [system] Message: -67.8
000+00:00:00.000 I 256: [command] Calling command system/message (send a message) with value -67.8
000+00:00:00.000 D 257: [emsesp] Schedule command 'system/message' with data '-67.8' was successful
000+00:00:00.000 D 258: [emsesp] Schedule test11: URL command successful with http code 200
000+00:00:00.000 D 259: [command] Calling command boiler/values
000+00:00:00.000 D 260: [command] Calling command boiler/commands (list all commands)
000+00:00:00.000 D 261: [command] Calling command boiler/values
000+00:00:00.000 D 262: [command] Calling command boiler/info (list all values)
000+00:00:00.000 D 263: [command] Calling command boiler/entities (list all entities)
000+00:00:00.000 D 264: [command] Fetched device entity/attributes for boiler/comfort
000+00:00:00.000 D 265: [emsesp] [DEBUG] fetching single attribute value
000+00:00:00.000 D 266: [command] Fetched device entity/attributes for boiler/comfort/value
000+00:00:00.000 D 267: [emsesp] [DEBUG] fetching single attribute fullname
000+00:00:00.000 D 268: [command] Fetched device entity/attributes for boiler/comfort/fullname
000+00:00:00.000 D 269: [command] Fetched device entity/attributes for boiler/outdoortemp
000+00:00:00.000 D 270: [emsesp] [DEBUG] fetching single attribute writeable
000+00:00:00.000 D 271: [command] Fetched device entity/attributes for boiler/chargetype/writeable
000+00:00:00.000 D 272: [emsesp] [DEBUG] fetching single attribute value
000+00:00:00.000 D 273: [command] Fetched device entity/attributes for boiler/flamecurr/value
000+00:00:00.000 D 274: [command] Fetched device entity/attributes for custom/values
000+00:00:00.000 D 275: [command] Fetched device entity/attributes for custom/seltemp
000+00:00:00.000 D 276: [command] Fetched device entity/attributes for system/info
000+00:00:00.000 D 277: [command] Fetched device entity/attributes for system/settings/locale
000+00:00:00.000 D 278: [command] Fetched device entity/attributes for scheduler/info
000+00:00:00.000 D 279: [command] Fetched device entity/attributes for scheduler/test_scheduler
000+00:00:00.000 D 280: [command] Fetched device entity/attributes for temperaturesensor/test_sensor2
000+00:00:00.000 D 281: [command] Fetched device entity/attributes for temperaturesensor/0B_0C0D_0E0F_1011
000+00:00:00.000 D 282: [command] Fetched device entity/attributes for temperaturesensor/test_sensor2/value
000+00:00:00.000 D 283: [command] Fetched device entity/attributes for analogsensor/values
000+00:00:00.000 D 284: [command] Fetched device entity/attributes for analogsensor/test_analog1
000+00:00:00.000 D 285: [command] Fetched device entity/attributes for analogsensor/test_analog1/offset
000+00:00:00.000 W 286: [command] Command failed: unknown device boiler2
000+00:00:00.000 W 287: [command] Command failed: unknown command bad
000+00:00:00.000 W 288: [command] Command failed: unknown command bad/value
000+00:00:00.000 D 289: [emsesp] [DEBUG] fetching single attribute valu
000+00:00:00.000 W 290: [command] Command failed: unknown command comfort/valu
000+00:00:00.000 W 291: [command] Command failed: unknown command settings/locale2
000+00:00:00.000 W 292: [command] Command failed: unknown command test_scheduler2
000+00:00:00.000 W 293: [command] Command failed: unknown command seltemp2
000+00:00:00.000 W 294: [command] Command failed: unknown command test_sensor20
000+00:00:00.000 W 295: [command] Command failed: unknown command 0B_0C0D_0E0F_XXXX
000+00:00:00.000 W 296: [command] Command failed: unknown command test_sensor2/bad
000+00:00:00.000 W 297: [command] Command failed: unknown command test_analog1/bad
000+00:00:00.000 W 298: [command] Command failed: unknown command test_analog10
000+00:00:00.000 W 299: [command] Command failed: unknown command test_analog10/bad
```

**Comment by MichaelDvP** [comment]
Yes, this message is from here:
https://github.com/emsesp/EMS-ESP32/blob/152b7bdee2a4926c74e9844c11e899fc717f6260/src/command.cpp#L339-L340
We have to avoid to set a message if cf exists.

**Pull request closed without merging**
