### PR TITLE
fix bug when traversing ems devices when using cmd allvalues

### PR DESCRIPTION
**Pull request by proddy**
use emsdevice->uniqueid for displaying values instead of searching the factory for registered types. when displaying more than 1 thermostat it got messed up

### CODE REVIEW

**Review by MichaelDvP — APPROVED** [review]

**Comment by MichaelDvP** [comment]
I'm not sure if this is this commit, but the devices are mixed now, api/thermostat/values gives me the mixer values, etc.

**Comment by MichaelDvP** [comment]
Oh, now i see, i've missed that: 
It is intended that all thermostats go to **one** publish, each thermostats uses different tags/hcs and there are no identical values.
Also we have one thermostat_data, mixer_data,, etc.  in mqtt. Checking the device_type is right.

**Comment by proddy** [comment]
yes, I see as well. Missed that. I'll revert back

**Comment by proddy** [comment]
will do a new PR

**Pull request merged**
