### PR TITLE
add tag after fullname instead of before

### PR DESCRIPTION
**Pull request by proddy**
For https://github.com/emsesp/EMS-ESP32/issues/1338

### CODE REVIEW

**Comment by proddy** [comment]
@MichaelDvP would you mind checking this to see if there is anything broken downstream that I may have missed? I've added TODOs in 3 places to track the changes.

**Comment by MichaelDvP** [comment]
Tested, works so far. It's a bit unfamiliar with tags appended, especally the hc, the commands/mqtt have them in front, but ok. Sorting alphabetical now shows different hcs in line, e.g. all seltemps together. 

But this does not solve #1338. There the tag itself leads to the complain. He dont want have these dhw entities taged. 
For boiler we have all dhw related taged with dhw, but some heatpump entities were introduces withot tag, e.g. 
boiler/wwworkm was taged "dhw active time", heatpumps boiler/uptimecompww "operating time compressor" was not taged but named with fullname "operating time compressor dhw". Because of #1301 i've added the missing dhw tags to have all in line, but this leads to this complain, i think because the tag also is used in HA.  
But i still think it's right to tag these dhw related entities and every change will have someone who complains.

The other complain https://github.com/emsesp/EMS-ESP32/issues/1338#issuecomment-1774154213 is the boiler/info command shows fullnames and will always break his database on a renaming.

**Comment by proddy** [comment]
> Tested, works so far. It's a bit unfamiliar with tags appended, especally the hc, the commands/mqtt have them in front, but ok. Sorting alphabetical now shows different hcs in line, e.g. all seltemps together.
> 
> But this does not solve #1338. There the tag itself leads to the complain. He dont want have these dhw entities taged. For boiler we have all dhw related taged with dhw, but some heatpump entities were introduces withot tag, e.g. boiler/wwworkm was taged "dhw active time", heatpumps boiler/uptimecompww "operating time compressor" was not taged but named with fullname "operating time compressor dhw". Because of #1301 i've added the missing dhw tags to have all in line, but this leads to this complain, i think because the tag also is used in HA. But i still think it's right to tag these dhw related entities and every change will have someone who complains.
> 
> The other complain [#1338 (comment)](https://github.com/emsesp/EMS-ESP32/issues/1338#issuecomment-1774154213) is the boiler/info command shows fullnames and will always break his database on a renaming.

I see. Then we should just leave it be, and not change anything. Unless we want to tag every entity. Shall I revert this PR?

**Comment by MichaelDvP** [comment]
> Shall I revert this PR?

As you like, the change does not make a big difference and there are always some users complaining on any change. 
Actually i prefere the prefix, but i think only because it's familiar.

**Comment by proddy** [comment]
I'll leave it the old way, and we can always make a new Settings option to prefix or suffix the tag - its cosmetics only

**Pull request merged**
