### PR TITLE
Add FR language to EMS-ESP

### PR DESCRIPTION
**Pull request by PopaSchKing**
Hi, 

After a bit of work, here's the translation to French.
I tested the interface and built the framework without issue.

image

Let me know if there are things missing or not working, I'll be able to work on it quickly.

Cheers

### CODE REVIEW

**Comment by proddy** [comment]
..and I can't find any faults. You did a really solid job. @MichaelDvP  ?

**Review by MichaelDvP — APPROVED** [review]
Good work. 

@proddy: Should we sort the languages alphabetical in the drop down lists? 
Maybe EN extra as: `EN <divider> DE, FR, NL, NO, PL, SE`

**Comment by proddy** [comment]
> Good work.
> 
> @proddy: Should we sort the languages alphabetical in the drop down lists? Maybe EN extra as: `EN <divider> DE, FR, NL, NO, PL, SE`

yes I like that idea.

**Comment by proddy** [comment]
I'll merge this change and we can adjust the order afterwards

**Pull request merged**
