### PR TITLE
added version upgrade/downgrade #832

### PR DESCRIPTION
**Pull request by proddy**
includes some other minor things

when upgrade <3.5.0b13 it will set the MQTT HA Entity ID format to 0, which is the old method using the long names

### CODE REVIEW

**Review by MichaelDvP — APPROVED** [review]
The changes to ems-esp are looking ok. I have not understand what this library do. +30k code and 6k ram just for comparing two version strings? There must be something other.

**Comment by proddy** [comment]
> The changes to ems-esp are looking ok. I have not understand what this library do. +30k code and 6k ram just for comparing two version strings? There must be something other.

yes, it's indeed a lot of code but uses Templates so only compiles the code it uses. I think the overhead in mem is in the std:: libraries it uses. I'll search around again for alternative libraries. What's important is that it can parse the major/minor/patch from a version string.

**Comment by MichaelDvP** [comment]
I think ot's not the lib, most of the memory change comes from the c++17 update, also i have compiled with a updated dev-platform, that also produces more code. Will go back to standard...

**Comment by proddy** [comment]
@MichaelDvP I rolled back to c++11, it indeed saves about 2k ram

**Pull request merged**
