### PR TITLE
Changes from my testbuild

### PR DESCRIPTION
**Pull request by MichaelDvP**

### CODE REVIEW

**Comment by MichaelDvP** [comment]
Or should we also use dev2 as testbuild? S3 is now wthout SSL option, and mqtt takes 5k heap for own task. I hope this will not stay to next release.

**Comment by proddy** [comment]
i think a dev2 is better to hunt down the cause of the freezes

**Comment by MichaelDvP** [comment]
ok, i close this.

**Comment by proddy** [comment]
@MichaelDvP created a dev2. https://github.com/emsesp/EMS-ESP32/tree/dev2

**Pull request closed without merging**
