### PR TITLE
Update locale_translations.h

### PR DESCRIPTION
**Pull request by misa1515**
added new language - slovak

### CODE REVIEW

**Comment by proddy** [comment]
nice, that was quite a lot of work to do. Are you also planning to translate the web interface?

And you'll need to add the language to the Web settings. See https://emsesp.github.io/docs/Adding-Languages/#how-to-add-language-xy-to-the-webui

**Comment by MichaelDvP** [comment]
I've tried to merge to a testbuild. Platformio seems to hang up on the characters `č` and 'ď', not finding some includes after that and stops compiling. Maybe a charset setting, but i have not found a solution yet. The other special characters do not have this effect.
BTW: We also should include the special characters in webfont.

**Comment by misa1515** [comment]
@proddy one question: how to create new directory in interface/src/ "sk"?

**Comment by proddy** [comment]
I can create it for you and all you need to do is update the index.ts file

**Comment by proddy** [comment]
can you merge to dev please?

**Pull request closed without merging**
