### PR TITLE
scheduler functions #2115, uptime notset-value #2109, device custom name #2073

### PR DESCRIPTION
**Pull request by MichaelDvP**
my devcies does not show telegram 01 offset 27. This build reads the name after registering 02 version and sets the custom name if this is not set by user, so it can always be overwritten by user. But not tested.

The change in telegram sets for telegram-reads the correct  length. This was a  test for the faulty mix communication but does not help. But it's more clean.

### CODE REVIEW

**Comment by proddy** [comment]
Great to see those scheduler functions. Would you mind adding a line to https://emsesp.org/Configuring/#conditions so we record it. Also mention it in the ChangeLog.

For the name (offset 27), let's see what people think. It may be a little strange for some e.g. a Logatherm WLW heat pump gets renamed to "XCU_THH".

**Comment by mattreim** [comment]
@proddy Is the sonar message (`Make sure use of "strlen" is safe here.`) really a problem?

**Comment by MichaelDvP** [comment]
It's a warning and strlen is safe in this case: the name is generated with strlcpy, so it's always null terminated within size limit.

**Comment by proddy** [comment]
yes, it's ok. I've updated Sonar

**Comment by mattreim** [comment]
Thanks for the information

**Pull request merged**
