### PR TITLE
replace react with preact #1224

### PR DESCRIPTION
**Pull request by proddy**

### CODE REVIEW

**Review by MichaelDvP — APPROVED** [review]
Have only compiled and tested, works good, no issues found.

**Comment by proddy** [comment]
I'm running on my production system and so far no issues. The nice thing is that its also free'd up 4KB of heap somehow. But that could be because I'm on 6.3.2 espressif and no longer 5.3.0. 

So TLS should now in theory work on all platform builds?

**Comment by MichaelDvP** [comment]
> So TLS should now in theory work on all platform builds?

Maybe fit to 2M partition, but i think TSL takes to much heap for esp32 without PSRAM.

**Comment by proddy** [comment]
ok. let's keep dev2 running for a few more days and then merge into dev, then a week or two and then into main. Then I can go on holiday (with my new aprilia)

**Comment by proddy** [comment]
nice! RSV Mille Factory R. It was semi-road legal but I put a race exhaust on it

**Pull request merged**
