### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Vikingn**
Translated Norwegian and added space for tr at the end of each line

### CODE REVIEW

**Comment by proddy** [comment]
Nice @Vikingn. Glad you got the PR working. @MichaelDvP I'm out this weekend and most of next week so if you beat me too it could you verify. Otherwise I'll pick it up on Friday 24/Feb

**Comment by MichaelDvP** [comment]
the locale_translations.h needs manual merge. As far as i see all is ok, only for "seconds" the edited column is wrong. Good work.

@Vikingn If you are ok with it, i can manual merge to my dev build and make a new PR.  Or do you want to do the manual merge to actual dev version and update this PR?

**Comment by MichaelDvP** [comment]
Sorry, i don't know the best/right way to merge. I normally try in VSC. But inthis case i've downloaded your file and compare it with winmerge. It's only that we've changed the the macro in the first 270 lines to MAKE_WORD_TRANSLATION, to differ between the lists withut a mqtt entitiy and the entities (stay at MAKE_TRANSLATION). This can be changed easily searh and replace in an editor.

**Comment by Vikingn** [comment]
I have used vsc and Im home in 20 min

Sendt fra min iPhone

20. mar. 2023 kl. 17:24 skrev MichaelDvP ***@***.***>:

﻿

Sorry, i don't know the best/right way to merge. I normally try in VSC. But inthis case i've downloaded your file and compare it with winmerge. It's only that we've changed the the macro in the first 270 lines to MAKE_WORD_TRANSLATION, to differ between the lists withut a mqtt entitiy and the entities (stay at MAKE_TRANSLATION). This can be changed easily searh and replace in an editor.

**Comment by Vikingn** [comment]
Hi ***@***.***> !

I will try myself then.

I saw it was something that has changesd on line 271 when I translated it.

I try in just some min and will make a New PR.

If I need help I will mail you again.

You can sms/Call me too  if you see something wrong. +47 99593527

Hope to get the Norwegian translation better.

Could it be possible to do it in Excel or something so its possible to hide all/some Languages and then just have English/Norwegian or Swedish that are similar up at the same time?  Hide the others. Then its easier to translate.

Proddy helped me a week ago via google Meeting. But I cant get the yarn run standalone to show my New translations.

I missed something there.  The web page comes up.


Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: mandag 20. mars 2023 kl. 17.24
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Dev (PR #1129)


Sorry, i don't know the best/right way to merge. I normally try in VSC. But inthis case i've downloaded your file and compare it with winmerge. It's only that we've changed the the macro in the first 270 lines to MAKE_WORD_TRANSLATION, to differ between the lists withut a mqtt entitiy and the entities (stay at MAKE_TRANSLATION). This can be changed easily searh and replace in an editor.

**Comment by Vikingn** [comment]
Hi Michel !

I tried to change the file.

Do you get it bach now on GH ?


Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: mandag 20. mars 2023 kl. 17.24
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Dev (PR #1129)


Sorry, i don't know the best/right way to merge. I normally try in VSC. But inthis case i've downloaded your file and compare it with winmerge. It's only that we've changed the the macro in the first 270 lines to MAKE_WORD_TRANSLATION, to differ between the lists withut a mqtt entitiy and the entities (stay at MAKE_TRANSLATION). This can be changed easily searh and replace in an editor.

**Comment by MichaelDvP** [comment]
Something gone wrong, you have added 56 files from an older version.

**Comment by Vikingn** [comment]
Hi !

Can look at in the evening or send you my file.

Sendt fra min iPhone

21. mar. 2023 kl. 08:56 skrev MichaelDvP ***@***.***>:

﻿

Something gone wrong, you have added 56 files from an older version.

**Comment by Vikingn** [comment]
Hi !

Think I will try to delete all.. fork it again and just replace my translation file


Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: tirsdag 21. mars 2023 kl. 19.12
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Dev (PR #1129)


Hmm, it shows me still 58 changed files
[grafik]<https://user-images.githubusercontent.com/59284019/226702223-e2a157aa-227f-4c37-97eb-638ddef32489.png>
and your repo is 28 commits back
[grafik]<https://user-images.githubusercontent.com/59284019/226702404-fe93708c-91f9-4ed0-8bf2-0d7fefc0848e.png>

I suggest you save your two files, fetch the actual dev branch new from ems-esp, copy your files in and commit this.
Or i can take these two files from yout repo and make a new PR.

**Comment by Vikingn** [comment]
Better now ?

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: tirsdag 21. mars 2023 kl. 19.12
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [emsesp/EMS-ESP32] Dev (PR #1129)


Hmm, it shows me still 58 changed files
[grafik]<https://user-images.githubusercontent.com/59284019/226702223-e2a157aa-227f-4c37-97eb-638ddef32489.png>
and your repo is 28 commits back
[grafik]<https://user-images.githubusercontent.com/59284019/226702404-fe93708c-91f9-4ed0-8bf2-0d7fefc0848e.png>

I suggest you save your two files, fetch the actual dev branch new from ems-esp, copy your files in and commit this.
Or i can take these two files from yout repo and make a new PR.

**Pull request closed without merging**
